# Generated by Django 5.0.4 on 2025-04-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Рабочие часы')),
                ('map_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Контакты футера',
                'verbose_name_plural': 'Контакты футера',
            },
        ),
    ]
