# Generated by Django 5.0.4 on 2025-04-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talant_app', '0002_footercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('documents_title', models.CharField(default='Необходимые документы', max_length=200, verbose_name='Заголовок блока документов')),
                ('documents_list', models.TextField(help_text='Перечислите документы через запятую или в формате HTML списка', verbose_name='Список документов')),
                ('subjects_title', models.CharField(default='Профилирующие предметы', max_length=200, verbose_name='Заголовок блока предметов')),
                ('subjects_list', models.TextField(help_text='Перечислите предметы через запятую или в формате HTML списка', verbose_name='Список предметов')),
                ('additional_info_title', models.CharField(default='Дополнительная информация', max_length=200, verbose_name='Заголовок дополнительной информации')),
                ('additional_info', models.TextField(verbose_name='Дополнительная информация')),
                ('reception_info', models.CharField(max_length=200, verbose_name='Информация о приёме документов')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('official_site_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на официальный сайт')),
            ],
            options={
                'verbose_name': 'Как поступить',
                'verbose_name_plural': 'Как поступить',
            },
        ),
    ]
