# Generated by Django 5.0.4 on 2025-04-09 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talant_app', '0003_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParliament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('goals_title', models.CharField(default='Цели и задачи', max_length=200, verbose_name='Заголовок целей и задач')),
                ('goals_list', models.TextField(help_text='Перечислите цели через запятую или в формате HTML списка', verbose_name='Список целей и задач')),
                ('activities_title', models.CharField(default='Направления деятельности', max_length=200, verbose_name='Заголовок направлений деятельности')),
            ],
            options={
                'verbose_name': 'Студенческий парламент',
                'verbose_name_plural': 'Студенческий парламент',
            },
        ),
        migrations.CreateModel(
            name='ParliamentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название направления')),
                ('description', models.TextField(verbose_name='Описание направления')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='talant_app.studentparliament', verbose_name='Парламент')),
            ],
            options={
                'verbose_name': 'Направление деятельности парламента',
                'verbose_name_plural': 'Направления деятельности парламента',
            },
        ),
    ]
