# Generated by Django 5.0.4 on 2025-04-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talant_app', '0005_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Правила внутреннего распорядка', max_length=200, verbose_name='Заголовок страницы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('general_title', models.CharField(default='Общие положения', max_length=200, verbose_name='Заголовок общих положений')),
                ('general_rules', models.TextField(help_text='Перечислите правила через запятую или в формате HTML списка', verbose_name='Список общих положений')),
                ('behavior_title', models.CharField(default='Поведение в учебном заведении', max_length=200, verbose_name='Заголовок поведения')),
                ('behavior_rules', models.TextField(help_text='Перечислите правила через запятую или в формате HTML списка', verbose_name='Список правил поведения')),
                ('discipline_title', models.CharField(default='Дисциплинарные меры', max_length=200, verbose_name='Заголовок дисциплинарных мер')),
                ('discipline_rules', models.TextField(help_text='Перечислите меры через запятую или в формате HTML списка', verbose_name='Список дисциплинарных мер')),
                ('conclusion', models.TextField(verbose_name='Заключение')),
            ],
            options={
                'verbose_name': 'Правило внутреннего распорядка',
                'verbose_name_plural': 'Правила внутреннего распорядка',
            },
        ),
    ]
