# Generated by Django 5.0.4 on 2025-04-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talant_app', '0006_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название расписания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schedules/', verbose_name='Изображение')),
                ('google_drive_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Google Drive')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
