# Generated by Django 5.0.4 on 2025-04-09 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talant_app', '0007_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('goals_title', models.CharField(default='Цели аккредитации', max_length=200, verbose_name='Заголовок целей')),
                ('goals_list', models.TextField(help_text='Перечислите цели через запятую или в формате HTML списка', verbose_name='Список целей')),
                ('documents_title', models.CharField(default='Документы аккредитации', max_length=200, verbose_name='Заголовок документов')),
            ],
            options={
                'verbose_name': 'Аккредитация',
                'verbose_name_plural': 'Аккредитация',
            },
        ),
        migrations.CreateModel(
            name='AccreditationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('description', models.TextField(verbose_name='Описание документа')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на файл')),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='talant_app.accreditation', verbose_name='Аккредитация')),
            ],
            options={
                'verbose_name': 'Документ аккредитации',
                'verbose_name_plural': 'Документы аккредитации',
            },
        ),
    ]
